# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('dataEHoraDeInicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataEHoraDeInicio')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
            ],
        ),
        migrations.RemoveField(
            model_name='artigoautor',
            name='artigoCientifico',
        ),
        migrations.RemoveField(
            model_name='artigoautor',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='artigocientifico',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='pessoa_ptr',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='realizador',
        ),
        migrations.RemoveField(
            model_name='eventocientifico',
            name='evento_ptr',
        ),
        migrations.RemoveField(
            model_name='inscricoes',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='inscricoes',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='inscricoes',
            name='tipoInscricao',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='pessoa_ptr',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='pessoa_ptr',
        ),
        migrations.DeleteModel(
            name='ArtigoAutor',
        ),
        migrations.DeleteModel(
            name='ArtigoCientifico',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='EventoCientifico',
        ),
        migrations.DeleteModel(
            name='Inscricoes',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='PessoaFisica',
        ),
        migrations.DeleteModel(
            name='PessoaJuridica',
        ),
        migrations.DeleteModel(
            name='TipoInscricao',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Usuario'),
        ),
        migrations.AddField(
            model_name='projetousuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Usuario'),
        ),
    ]
